# Dimensions of grid
GRID_WIDTH = 11
GRID_LENGTH = 11

# Dimensions of tiles in grid
TILE_WIDTH = 50
TILE_HEIGHT = 50
#TILE_MARGIN = 5

# Window dimensions
#WINDOW_SIZE = (GRID_LENGTH * (TILE_WIDTH + TILE_MARGIN), GRID_WIDTH * (TILE_WIDTH + TILE_MARGIN))
WINDOW_SIZE = (GRID_LENGTH * TILE_WIDTH, GRID_WIDTH * TILE_WIDTH)